package main

import (
    "github.com/labstack/echo/v4"
    "net/http"
    "se-test/api/negativations"
    "se-test/config"
    "se-test/db"
    "se-test/handler"
    "se-test/router"
    "strconv"

    echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
    _ "se-test/docs"                             // docs is generated by Swag CLI, you have to import it.
)

// @title Se-Test
// @version 1.0
// @description Se-test Bruno Luiz Katzjarowski
// @title Se-test Bruno Luiz Katzjarowski

// @host 127.0.0.1:9090
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.basic BasicAuth
// @in header
// @name Authorization
func main() {

    // Echo instance
    r := router.New()

    r.GET("/swagger/*", echoSwagger.WrapHandler)

    // add status request
    r.GET("/", apiStatus)

    // Create "v1" group
    v1 := r.Group("/api")

    // create a db handler
    d := db.NewDbHandler()

    n := negativations.NewHandler(d)
    h := handler.NewHandler(n)

    h.Register(v1)
    r.Logger.Fatal(r.Start(":" + strconv.FormatInt(config.GetPortEnv(), 10)))
}

// Root Handler
func apiStatus(ctx echo.Context) error {
    return ctx.String(http.StatusOK, "API - STATUS - OK")
}
